### ISSUE TITLE
KeyError: 'Q'

### ISSUE THREAD

**Issue by jakobabesser** [c4dm/dcase-few-shot-bioacoustic#20]
Hi, when running 

`python evaluation.py -pred_file="../results/pred_all.csv" -ref_files_path="C:\datasets\dcase_2022_task_5\Development_Set\Validation_Set" -team_name=TESTtean -dataset=VAL -savepath="../results/"`

to start the `evaluation.py` script, I got the following error message:

`
Evaluation for: TESTtean VAL
#423-487.wav {'TP': 0, 'FP': 33, 'FN': 4, 'total_n_pos_events': 4}
#97-113.wav {'TP': 4, 'FP': 8, 'FN': 6, 'total_n_pos_events': 10}
BUK1_20181011_001004.wav {'TP': 14, 'FP': 270, 'FN': 17, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 1, 'FP': 771, 'FN': 23, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 937, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 10, 'FP': 27, 'FN': 7, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 37, 'FP': 153, 'FN': 51, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 5, 'FP': 83, 'FN': 18, 'total_n_pos_events': 23}
DCASE2021-ML_126376.wav {'TP': 27, 'FP': 14, 'FN': 67, 'total_n_pos_events': 94}
DCASE2021-ML_129696.wav {'TP': 15, 'FP': 23, 'FN': 61, 'total_n_pos_events': 76}
DCASE2021-ML_131198.wav {'TP': 4, 'FP': 4, 'FN': 0, 'total_n_pos_events': 4}
DCASE2021-ML_131369.wav {'TP': 33, 'FP': 6, 'FN': 7, 'total_n_pos_events': 40}
DCASE2021-ML_168236.wav {'TP': 47, 'FP': 149, 'FN': 63, 'total_n_pos_events': 110}
DCASE2021-ML_176488.wav {'TP': 9, 'FP': 5, 'FN': 0, 'total_n_pos_events': 9}
DCASE2021-ML_190099.wav {'TP': 12, 'FP': 6, 'FN': 3, 'total_n_pos_events': 15}
DCASE2021-ML_191491.wav {'TP': 9, 'FP': 5, 'FN': 0, 'total_n_pos_events': 9}
DCASE2021-ML_197045.wav {'TP': 74, 'FP': 6, 'FN': 0, 'total_n_pos_events': 74}
DCASE2021-ML_268995.wav {'TP': 9, 'FP': 3, 'FN': 1, 'total_n_pos_events': 10}
DCASE2021-ML_273164.wav {'TP': 7, 'FP': 146, 'FN': 143, 'total_n_pos_events': 150}
DCASE2021-ML_37045.wav {'TP': 12, 'FP': 5, 'FN': 0, 'total_n_pos_events': 12}
DCASE2021-ML_521435.wav {'TP': 50, 'FP': 6, 'FN': 8, 'total_n_pos_events': 58}
DCASE2021-ML_53963.wav {'TP': 78, 'FP': 5, 'FN': 0, 'total_n_pos_events': 78}
DCASE2021-ML_72010931.wav {'TP': 57, 'FP': 6, 'FN': 2, 'total_n_pos_events': 59}
DCASE2021-ML_89792.wav {'TP': 29, 'FP': 5, 'FN': 0, 'total_n_pos_events': 29}
ME1.wav {'TP': 10, 'FP': 20, 'FN': 1, 'total_n_pos_events': 11}
ME2.wav {'TP': 38, 'FP': 32, 'FN': 3, 'total_n_pos_events': 41}
R4_cleaned recording_13-10-17.wav {'TP': 4, 'FP': 1, 'FN': 15, 'total_n_pos_events': 19}
R4_cleaned recording_16-10-17.wav {'TP': 12, 'FP': 3, 'FN': 22, 'total_n_pos_events': 34}
R4_cleaned recording_17-10-17.wav {'TP': 23, 'FP': 2, 'FN': 13, 'total_n_pos_events': 36}
R4_cleaned recording_TEL_19-10-17.wav {'TP': 6, 'FP': 1, 'FN': 48, 'total_n_pos_events': 54}
R4_cleaned recording_TEL_20-10-17.wav {'TP': 20, 'FP': 3, 'FN': 45, 'total_n_pos_events': 65}
R4_cleaned recording_TEL_23-10-17.wav {'TP': 20, 'FP': 2, 'FN': 64, 'total_n_pos_events': 84}
R4_cleaned recording_TEL_24-10-17.wav {'TP': 15, 'FP': 1, 'FN': 84, 'total_n_pos_events': 99}
R4_cleaned recording_TEL_25-10-17.wav {'TP': 39, 'FP': 3, 'FN': 61, 'total_n_pos_events': 100}
Traceback (most recent call last):
  File "C:\Users\abr\Miniconda3\envs\alfpaka_env\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Q'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "evaluation.py", line 319, in <module>
    evaluate( args.pred_file, args.ref_files_path, args.team_name, args.dataset, args.savepath)
  File "evaluation.py", line 212, in evaluate
    total_n_pos_events_in_audiofile =  len(select_events_with_value(ref_events_this_audiofile, value=POS_VALUE))
  File "evaluation.py", line 32, in select_events_with_value
    indexes_list = data_frame.index[data_frame["Q"] == value].tolist()
  File "C:\Users\abr\Miniconda3\envs\alfpaka_env\lib\site-packages\pandas\core\frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\abr\Miniconda3\envs\alfpaka_env\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Q'
`

It seems that he is able to load the reference annotations as well as my predictions, however I don't get the final results. Any idea what causes this error? Thank you!

**Comment by inesnolas** [comment]
Hi, 
That error seems to indicate a problem with the header of the annotation files, specifically for the audiofiles where you don;t generate any predictions.( check the DCASE2021-ML_40509.csv from the ML set )
I suspect there is a problem with your downloaded data, could you check for that?

I tried to simulate your problem but everything is running fine on my end. if you send me your predictions file I can test that as well.
